### PR TITLE
#161035960 create login page

### PR DESCRIPTION
**Pull request by wandesky**
#### What does this PR do?
Create login page for Store Manager web app

#### Description of Task to be completed?
Provide an interface for the user to log in.

#### How should this be manually tested?
Clone the repo using ```git clone https://github.com/wandesky/store-manager.git```
Change/Switch to the project's directory ```cd store-manager```
Switch to the login page branch ``` git checkout ft-login-page-161035960```
Open the index.html file in your browser 

#### Any background context you want to provide?
* I have implemented @KelynPNjeri feedback to make the header fill the whole page width.

#### What are the relevant pivotal tracker stories?
[#161035960](https://www.pivotaltracker.com/story/show/161035960)
[#161041113](https://www.pivotaltracker.com/story/show/161041113)

#### Screenshots (header fills page width)
image

#### Questions:
Is there any other way I can improve my login page? Leave your response in the review section below or by clicking the _*Review Changes/New Issue*_ button found [here](https://github.com/wandesky/store-manager/pull/1/files).

### CODE REVIEW

**Comment by charitymarani** [comment]
what happens when you are not logged in and you click add product?

**Comment by cod3smith** [comment]
The UI looks good but I would suggest making the navbar fill the screen in terms of width.
And Plus @charitymarani  has a point.

**Comment by Makavura** [comment]
So @KelynPNjeri and @charitymarani aren't we getting ahead of ourselves? there is no functionality being implemented yet, right?

**Comment by Makavura** [comment]
The UI is good. However, in my opinion, there seems to be a disparity with the fonts

**Comment by wandesky** [comment]
> 
> 
> what happens when you are not logged in and you click add product?

You will be prompted to log-in (although this implementation will come later, for now, the user will be directed to the add products, page)

**Comment by wandesky** [comment]
> 
> 
> The UI is good. However, in my opinion, there seems to be a disparity with the fonts

I used Roboto for all text. (It is only the logo that has a different version of sans-serrif)

**Comment by DennisMufasa** [comment]
Hey, your PR looks good.

**Pull request merged**
