### PR TITLE
#161036036 create view sales page 

### PR DESCRIPTION
**Pull request by wandesky**
#### What does this PR do?
Create view sales records page for Store Manager web app

#### Description of Task to be completed?
Provide an interface for the user(attendant) to access all sales records.

#### How should this be manually tested?
Clone the repo using ```git clone https://github.com/wandesky/store-manager.git```
Change/Switch to the project's directory cd store-manager
Switch to the login page branch ```git checkout ft-view-sales-page-161036036```
Open the view-sales.html file in your browser

#### What are the relevant pivotal tracker stories?
[#161036036](https://www.pivotaltracker.com/story/show/161036036)
[#161066776](https://www.pivotaltracker.com/story/show/161066776) _@unah254's [peer review](https://github.com/wandesky/store-manager/pull/2#issuecomment-427926912) feedback [implementation](https://github.com/wandesky/store-manager/pull/2/commits/4205a493633a7292afdb1bec159ba032fb8d7515)_
[#161069956](https://www.pivotaltracker.com/story/show/161069956)_[ @kwanj-k](https://github.com/wandesky/store-manager/pull/2#issuecomment-427956388) and [ @waracci](https://github.com/wandesky/store-manager/pull/2#issuecomment-427961690) peer reviews [implementation](https://github.com/wandesky/store-manager/pull/2/commits/438afb157e5d2ae5d9fa62c854fc17615019cf7a)_

#### Screenshots (if appropriate)
Attendee's View of Sales Record

#### Questions:
Is there another suggestion as to how I can improve my view sales records page?

### CODE REVIEW

**Comment by unah254** [comment]
Nice UI.You could increase the size of the table

**Comment by wandesky** [comment]
> Nice UI.You could increase the size of the table

Hi @unah254 . I have implemented some changes based on your recommendations.

**Comment by kwanj-k** [comment]
U could include the name of attendant who sold the item

**Comment by wandesky** [comment]
> U could the name name of attendant who sold the item

@kwanj-k you have actually given me a brilliant idea. I am now going to make two sales records. One to be generated for the admin (which includes the names of the attendee that made the sale) and another one to be used by the attendee (which generates all the records made by that particular attendee).

**Comment by kwanj-k** [comment]
> > U could the name name of attendant who sold the item
> 
> @kwanj-k you have actually given me a brilliant idea. I am now going to make two sales records. One to be generated for the admin (which includes the names of the attendee that made the sale) and another one to be used by the attendee (which generates all the records made by that particular attendee).

its what am doing actually,hehe

**Comment by waracci** [comment]
Good UI especially the navbar. :+1: 
For the table, try adding some padding for each row.
`td{
padding: 6px;
}`

**Comment by wandesky** [comment]
> 
> 
> Good UI especially the navbar. 👍
> For the table, try adding some padding for each row.
> `td{ padding: 6px; }`

Thanks @waracci for the suggestion and code segment.

**Comment by Nicanor008** [comment]
@wandesky good UI, This is impressive work

**Comment by wandesky** [comment]
> 
> 
> @wandesky good UI, This is impressive work

Thank you @Nicanor008. I am still working to implement the feedback from @waracci and @kwanj-k .

**Comment by wandesky** [comment]
I have implemented both @waracci's and @kwanj-k's feedback.

**Comment by JoshuaKodhe** [comment]
Great UI

**Comment by Paulvitalis200** [comment]
All I can say is Wow!!! It's good.

**Comment by DennisMufasa** [comment]
looks good

**Pull request merged**
